# FTB Quests by DetraisMC

config-version: 1
update-checker: true

# Time in minutes between automatic database saves
auto-save-interval: 5

mysql-settings:

  # Enable MySQL
  # If false, SQLite will be used instead
  enabled: true

  hostname: 0.0.0.0
  port: 0
  database-name: ''

  user-name: ''
  user-password: ''

  use-ssl: false

  connection-pool-size: 3
