name: SkyfunUtils
author: DetraisMC
description: Slimefun Addon to help finite resource gamemode like skyblock, acid island, caveblock, etc
version: 1.0.0
main: dark.detraismc.skyfunutils.SkyfunUtils
api-version: 1.21
depend: [Slimefun]
