name: SpContentQuests
author: DetraisMC
description: Plugin inspired by mod FTB Quests to make player have a straight goal in server
version: 1.0
main: me.detraismc.spcontentquests.SpContentQuests
api-version: 1.21
softdepend: [MythicMobs, Slimefun, MMOItems, ItemsAdder, PlaceholderAPI]
commands:
  spcontentquests:
    description: SpContentQuests main command
    usage: /<command>
    aliases: [contentquests, contentquest, cquests, cquest, spcq, cq]
  questbook:
    description: Get the Quest Book
    usage: /<command>

permissions:
  spcontentquests.admin:
    description: Allows use of admin commands
    default: op
  spcontentquests.questbook:
    description: Allows use of /questbook command
    default: true
