name: FTBQuests
author: DetraisMC
description: Plugin inspired by mod FTB Quests to make player have a straight goal in server
version: 1.0
main: me.detraismc.ftbquests.FTBQuests
api-version: 1.21
commands:
  ftbquests:
    description: FTB Quests main command
    usage: /<command>
  questbook:
    description: Get the Quest Book
    usage: /<command>

permissions:
  ftbquests.admin:
    description: Allows use of admin commands
    default: op
  ftbquests.questbook:
    description: Allows use of /questbook command
    default: true
